package models

import RouteType
import commands.CommandException
import java.io.Serializable

/* CITY NAMES */
const val DARK_DIMENSION = "darkdimension"
const val GIBBORIM = "gibborim"
const val GALACTUS = "galactus"
const val ZENN_LA = "zennla"
const val KNOWHERE = "knowhere"
const val CHITAURI_SANCTUARY = "chitaurisanctuary"
const val ZEN_WHOBERI = "zenwhoberi"
const val EGO = "ego"
const val KITSON = "kitson"
const val CAVE_OF_THE_DRAGON = "caveofthedragon"
const val KUN_LUN = "kunlun"
const val VANAHEIM = "vanaheim"
const val TITAN = "titan"
const val VORMIR = "vormir"
const val SAKAAR = "sakaar"
const val XANDAR = "xandar"
const val CAVE_OF_AGES = "caveofages"
const val SURTURS_LAIR = "surturslair"
const val HALA = "hala"
const val SVARTLHEIM = "svartlheim"
const val NIFLHEIM = "niflheim"
const val CONTRAXIA = "contraxia"
const val QUANTUM_REALM = "quantumrealm"
const val ASGARD = "asgard"
const val NIDAVELLIR = "nidavellir"
const val YOTUNHEIM = "yotunheim"
const val HONG_KONG_SANCTUM = "hongkongsanctum"
const val WAKANDA = "wakanda"
const val SOKOVIA = "sokovia"
const val PYM_LABS = "pymlabs"
const val AVENGERS_HQ = "avengershq"
const val NEW_YORK_CITY = "newyorkcity"
const val TRISKELION = "triskelion"
const val HELICARRIER = "helicarrier"
const val KAMAR_TAJ = "kamartaj"
const val MUSPELHEIM = "muspelheim"
/* ROUTE NAMES */
const val DARKDIMENSION_GIBBORIM_1 = "darkdimension_gibborim_1"
const val DARKDIMENSION_GIBBORIM_2 = "darkdimension_gibborim_2"
const val CHITAURISANCTUARY_DARKDIMENSION = "chitaurisanctuary_darkdimension"
const val GALACTUS_GIBBORIM_1 = "galactus_gibborim_1"
const val GALACTUS_GIBBORIM_2 = "galactus_gibborim_2"
const val CHITAURISANCTUARY_GIBBORIM = "chitaurisanctuary_gibborim"
const val CHITAURISANCTUARY_VORMIR = "chitaurisanctuary_vormir"
const val CHITAURISANCTUARY_ZENWHOBERI = "chitaurisanctuary_zenwhoberi"
const val GIBBORIM_ZENWHOBERI = "gibborim_zenwhoberi"
const val EGO_GALACTUS = "ego_galactus"
const val EGO_ZENWHOBERI = "ego_zenwhoberi"
const val GALACTUS_ZENNLA_1 = "galactus_zennla_1"
const val GALACTUS_ZENNLA_2 = "galactus_zennla_2"
const val EGO_ZENNLA_1 = "ego_zennla_1"
const val EGO_ZENNLA_2 = "ego_zennla_2"
const val KNOWHERE_ZENNLA_1 = "knowhere_zennla_1"
const val KNOWHERE_ZENNLA_2 = "knowhere_zennla_2"
const val KITSON_KNOWHERE = "kitson_knowhere"
const val EGO_KITSON = "ego_kitson"
const val CAVEOFTHEDRAGON_KNOWHERE = "caveofthedragon_knowhere"
const val KNOWHERE_KUNLUN = "knowhere_kunlun"
const val CAVEOFTHEDRAGON_TITAN = "caveofthedragon_titan"
const val CAVEOFTHEDRAGON_VANAHEIM = "caveofthedragon_vanaheim"
const val CAVEOFTHEDRAGON_KUNLUN = "caveofthedragon_kunlun"
const val KUNLUN_VANAHEIM = "kunlun_vanaheim"
const val EGO_TITAN_1 = "ego_titan_1"
const val EGO_TITAN_2 = "ego_titan_2"
const val TITAN_ZENWHOBERI = "titan_zenwhoberi"
const val SAKAAR_ZENWHOBERI = "sakaar_zenwhoberi"
const val VORMIR_ZENWHOBERI = "vormir_zenwhoberi"
const val XANDAR_ZENWHOBERI = "xandar_zenwhoberi"
const val TITAN_VANAHEIM = "titan_vanaheim"
const val CAVEOFAGES_TITAN_1 = "caveofages_titan_1"
const val CAVEOFAGES_TITAN_2 = "caveofages_titan_2"
const val TITAN_XANDAR = "titan_xandar"
const val SURTURSLAIR_TITAN = "surturslair_titan"
const val SURTURSLAIR_VANAHEIM = "surturslair_vanaheim"
const val KUNLUN_SURTURSLAIR = "kunlun_surturslair"
const val HALA_KUNLUN = "hala_kunlun"
const val KUNLUN_SVARTLHEIM = "kunlun_svartlheim"
const val HONGKONGSANCTUM_VORMIR = "hongkongsanctum_vormir"
const val SAKAAR_VORMIR = "sakaar_vormir"
const val HONGKONGSANCTUM_SAKAAR = "hongkongsanctum_sakaar"
const val PYMLABS_SAKAAR = "pymlabs_sakaar"
const val NIDAVELLIR_SAKAAR = "nidavellir_sakaar"
const val SAKAAR_XANDAR_1 = "sakaar_xandar_1"
const val SAKAAR_XANDAR_2 = "sakaar_xandar_2"
const val CAVEOFAGES_XANDAR_1 = "caveofages_xandar_1"
const val CAVEOFAGES_XANDAR_2 = "caveofages_xandar_2"
const val CAVEOFAGES_SURTURSLAIR_1 = "caveofages_surturslair_1"
const val CAVEOFAGES_SURTURSLAIR_2 = "caveofages_surturslair_2"
const val HALA_SURTURSLAIR_1 = "hala_surturslair_1"
const val HALA_SURTURSLAIR_2 = "hala_surturslair_2"
const val HALA_SVARTLHEIM_1 = "hala_svartlheim_1"
const val HALA_SVARTLHEIM_2 = "hala_svartlheim_2"
const val NIFLHEIM_SVARTLHEIM = "niflheim_svartlheim"
const val CONTRAXIA_SURTURSLAIR = "contraxia_surturslair"
const val CONTRAXIA_HALA = "contraxia_hala"
const val CONTRAXIA_NIFLHEIM = "contraxia_niflheim"
const val ASGARD_CONTRAXIA = "asgard_contraxia"
const val CONTRAXIA_QUANTUMREALM = "contraxia_quantumrealm"
const val ASGARD_CAVEOFAGES_1 = "asgard_caveofages_1"
const val ASGARD_CAVEOFAGES_2 = "asgard_caveofages_2"
const val ASGARD_QUANTUMREALM = "asgard_quantumrealm"
const val ASGARD_NEWYORKCITY = "asgard_newyorkcity"
const val ASGARD_NIDAVELLIR_1 = "asgard_nidavellir_1"
const val ASGARD_NIDAVELLIR_2 = "asgard_nidavellir_2"
const val NIDAVELLIR_XANDAR = "nidavellir_xandar"
const val NEWYORKCITY_NIDAVELLIR_1 = "newyorkcity_nidavellir_1"
const val NEWYORKCITY_NIDAVELLIR_2 = "newyorkcity_nidavellir_2"
const val NIDAVELLIR_PYMLABS = "nidavellir_pymlabs"
const val HONGKONGSANCTUM_PYMLABS = "hongkongsanctum_pymlabs"
const val HONGKONGSANCTUM_WAKANDA = "hongkongsanctum_wakanda"
const val MUSPELHEIM_NIFLHEIM = "muspelheim_niflheim"
const val NIFLHEIM_YOTUNHEIM_1 = "niflheim_yotunheim_1"
const val NIFLHEIM_YOTUNHEIM_2 = "niflheim_yotunheim_2"
const val MUSPELHEIM_YOTUNHEIM = "muspelheim_yotunheim"
const val QUANTUMREALM_YOTUNHEIM = "quantumrealm_yotunheim"
const val KAMARTAJ_YOTUNHEIM = "kamartaj_yotunheim"
const val KAMARTAJ_MUSPELHEIM = "kamartaj_muspelheim"
const val HELICARRIER_KAMARTAJ = "helicarrier_kamartaj"
const val HELICARRIER_YOTUNHEIM_1 = "helicarrier_yotunheim_1"
const val HELICARRIER_YOTUNHEIM_2 = "helicarrier_yotunheim_2"
const val HELICARRIER_QUANTUMREALM = "helicarrier_quantumrealm"
const val NEWYORKCITY_QUANTUMREALM = "newyorkcity_quantumrealm"
const val HELICARRIER_TRISKELION_1 = "helicarrier_triskelion_1"
const val HELICARRIER_TRISKELION_2 = "helicarrier_triskelion_2"
const val HELICARRIER_NEWYORKCITY = "helicarrier_newyorkcity"
const val NEWYORKCITY_TRISKELION = "newyorkcity_triskelion"
const val AVENGERSHQ_TRISKELION_1 = "avengershq_triskelion_1"
const val AVENGERSHQ_TRISKELION_2 = "avengershq_triskelion_2"
const val AVENGERSHQ_NEWYORKCITY_1 = "avengershq_newyorkcity_1"
const val AVENGERSHQ_NEWYORKCITY_2 = "avengershq_newyorkcity_2"
const val NEWYORKCITY_PYMLABS = "newyorkcity_pymlabs"
const val PYMLABS_WAKANDA = "pymlabs_wakanda"
const val AVENGERSHQ_WAKANDA = "avengershq_wakanda"
const val AVENGERSHQ_SOKOVIA_1 = "avengershq_sokovia_1"
const val AVENGERSHQ_SOKOVIA_2 = "avengershq_sokovia_2"
const val SOKOVIA_WAKANDA_1 = "sokovia_wakanda_1"
const val SOKOVIA_WAKANDA_2 = "sokovia_wakanda_2"

class Route(val routeId: String, val cities: Set<String>, val numCars: Int, val type: RouteType, var ownerId: Int) : Serializable {
    val points: Int
        get() {
            return when (numCars) {
                1 -> 1
                2 -> 2
                3 -> 4
                4 -> 7
                5 -> 10
                6 -> 15
                else -> throw CommandException("Invalid number of cars for route.")
            }
        }
}