package command;

public enum CommandType {
    LOGIN, REGISTER, JOIN_GAME, LEAVE_GAME, CREATE_GAME,
    PLAYER_READY, POST_CHAT, START_GAME, LIST_GAMES,
    REFRESH_GAME_LIST, LOGIN_RESULT, REGISTER_RESULT;
}
